export const Arts = [
  {
    title: "Sold Arts",
    Pieces: [
      {
        id: "1",
        image:"/images/IMG-20230526-WA0001.jpg",
        image2: "",
        text: "Your Gaze Hits the Side of My Face Original Artwork",
        pricing: "$2950.00",
      },
      {
        id: "2",
        image: "/images/img 2.webp",
        image2: "",
        text: " it's all about place and time (2023) by Jenna Grey",
        pricing: "$3350.00",
      },
      {
        id: "4",
        image: "/images/img3.webp",
        text: " beauty in the field (2023) by Jenna Grey",
        image2: "",
        pricing: "$2950.00",
      },
      {
        id: "5",
        image: "/images/IMG-20230526-WA0005.jpg",
        image2: "",
        text: "aliveness the love of life (2022) by Jenna Grey",
        pricing: "$3350",
      },
      {
        id: "6",
        image: "/images/IMG-20230526-WA0006.jpg",
        image2: "",
        text: "aliveness the love of life (2023) by Jenna Grey",
        pricing: "$3500",
      },
      {
        id: "7",
        image: "/images/IMG-20230526-WA0007.jpg",
        image2: "",
        text: "the beauty of it (2022) by Jenna Grey",
        pricing: "$2950",
      },
    ],
  },
  {
    title: "Availabe Arts",
    Pieces: [
      {
        id: "16",
        image: "/images/gallery1.webp",
        image2: "",
        text: "  Jenna Grey MCS13 Original Artwork",
        pricing: "$3850.00",
      },
      {
        id: "17",
        image: "/images/gallery2.webp",
        image2: "",
        text: " Jenna Grey MCS14 Original Artwork",
        pricing: "$3350.00",
      },
      {
        id: "18",
        image: "/images/gallery3.webp",
        image2: "",
        text: " Jenna Grey MCS15 Original Artwork",
        pricing: "$3500.00",
      },
      {
        id: "18",
        image: "/images/img6.webp",
        image2: "",
        text: "when the sea retreated (2023) by Jenna Grey",
        pricing: "$2950.00",
      },
      {
        id: "19",
        image: "/images/gallery5.webp",
        image2: "",
        text: " Jenna Grey MCS16 Original Artwork",
        pricing: "$2950.00",
      },
      {
        id: "20",
        image: "/images/gallery6.webp",
        image2: "",
        text: "  Jenna Grey MCS17 Original Artwork",
        pricing: "$2950.00",
      },
      {
        id: "21",
        image: "/images/gallery7.webp",
        image2: "",
        text: "Jenna Grey Dear Vinca Original Artwork",
        pricing: "$3350.00",
        
        
      },
      {
        id: "22",
        image: "/images/gallery8.webp",
        image2: "",
        text: " Jenna Grey's Gallery View",
        pricing: "$3500.00 per (1)",
      },
      {
        id: "23",
        image: "/images/gallery9.webp",
        image2: "",
        text: " Jenna Grey MCS11 Original Artwork",
        pricing: "$2950.00",
      },
      {
        id: "24",
        image: "/images/gallery10.webp",
        image2: "",
        text: " Jenna Grey MCS10 Original Artwork",
        pricing: "$3350.00",
      },
      {
        id: "25",
        image: "/images/img4.webp",
        image2: "",
        text: " Jenna Grey MCS12 Original Artwork",
        pricing: "$3850.00",
      },
      {
        id: "26",
        image: "/images/gallery12.webp",
        image2: "",
        text: "Jenna Grey MCS22 Original Artwork",
        pricing: "$3500.00",
      },
      {
        id: "27",
        image: "/images/gallery13.webp",
        image2: "",
        text: "Jenna Grey's Gallery View (2)",
        pricing: "$3000.00 per(1)",
      },
      {
        id: "28",
        image: "/images/img5.webp",
        image2: "",
        text: "no expectation (2023) by Jenna Grey",
        pricing: "$3350.00",
      },
    ],
  },
];
