export const Arts = [
    {
        title:'Sold Arts',
        Pieces:[
            {
                id:'1',
                image:'https://1xruhttps://cdn.shopify.com/s/files/1/0570/1435/4081/files/JM-Rizzi-May2023-1-OG-1xRUN-1.jpg?v=1684946152n.com/products/original-1',
                image2:'',
                text:'Your Gaze Hits the Side of My Face Original Artwork',
            },
            {
                id:'2',
                image:'../components/assets/images/IMG-20230526-WA0002.jpg',
                image2:'',
                text:'',
            },
            {
                id:'3',
                image:'../components/assets/images/IMG-20230526-WA00016.jpg',
                image2:'',
                text:'',
            },
            {
                id:'4',
                image:'../components/assets/images/IMG-20230526-WA0004.jpg',
                text:'',
                image2:'',
            },
            {
                id:'5',
                image:'../components/assets/images/IMG-20230526-WA0005.jpg',
                image2:'',
                text:'',
            },
            {
                id:'6',
                image:'../components/assets/images/IMG-20230526-WA0006.jpg',
                image2:'',
                text:'',
            },
            {
                id:'7',
                image:'../components/assets/images/IMG-20230526-WA0007.jpg',
                image2:'',
                text:'',
            },
            {
                id:'8',
                image:'../components/assets/images/IMG-20230526-WA0008.jpg',
                image2:'',
                text:'',
            },
            {
                id:'9',
                image:'../components/assets/images/IMG-20230526-WA0009.jpg',
                image2:'',
                text:'',
            },
            {
                id:'10',
                image:'../components/assets/images/IMG-20230526-WA00010.jpg',
                image2:'',
                text:'',
            },
            {
                id:'11',
                image:'../components/assets/images/IMG-20230526-WA00011.jpg',
                image2:'',
                text:'',
            },
            {
                id:'12',
                image:'../components/assets/images/IMG-20230526-WA00012.jpg',
                image2:'',
                text:'',
            },
            {
                id:'13',
                image:'../components/assets/images/IMG-20230526-WA00013.jpg',
                image2:'',
                text:'',
            },
            {
                id:'14',
                image:'../components/assets/images/IMG-20230526-WA00014.jpg',
                image2:'',
                text:'',
            },
            {
                id:'15',
                image:'../components/assets/images/IMG-20230526-WA00015.jpg',
                image2:'',
                text:'',
            },
        ]
    },
    {
        title:'Availabe Arts',
        Pieces: [
            {
                id:'16',
                image:'../components/assets/images/gallery1.webp',
                image2:'',
                text:'',
            },
            {
                id:'1',
                image:'../components/assets/images/gallery2.webp',
                image2:'',
                text:'',
            },
            {
                id:'18',
                image:'../components/assets/images/gallery3.webp',
                image2:'',
                text:'',
            },
            {
                id:'18',
                image:'../components/assets/images/gallery4.webp',
                image2:'',
                text:'',
            },
            {
                id:'19',
                image:'../components/assets/images/gallery5.webp',
                image2:'',
                text:'',
            },
            {
                id:'20',
                image:'../components/assets/images/gallery6.webp',
                image2:'',
                text:'',
            },
            {
                id:'21',
                image:'../components/assets/images/gallery7.webp',
                image2:'',
                text:'',
            },
            {
                id:'22',
                image:'../components/assets/images/gallery8.webp',
                image2:'',
                text:'',
            },
            {
                id:'23',
                image:'../components/assets/images/gallery9.webp',
                image2:'',
                text:'',
            },
            {
                id:'24',
                image:'../components/assets/images/gallery10.webp',
                image2:'',
                text:'',
            },
            {
                id:'25',
                image:'../components/assets/images/gallery11.webp',
                image2:'',
                text:'',
            },
            {
                id:'26',
                image:'../components/assets/images/gallery12.webp',
                image2:'',
                text:'',
            },
            {
                id:'27',
                image:'../components/assets/images/gallery13.webp',
                image2:'',
                text:'',
            },
            {
                id:'28',
                image:'../components/assets/images/gallery14.webp',
                image2:'',
                text:'',
            },
        ]
    }
]